### ISSUE TITLE
"Thank You" section listing people who have helped

### ISSUE THREAD

**Issue by eddiejaoude** [WeRockTech/werocktech.github.io#14]
I always like to give credit where credit is due. People have helped me to move this along. Should there be a section/page listing these people?

**Comment by squeakcode** [comment]
I think acknowledgements are always a good idea! :)

**Comment by eddiejaoude** [comment]
I am still working on the wording / styling, but what do you think so far? Are you happy to be mentioned @charlottebrf & @squeakcode ?

<img width="1671" alt="screenshot 2016-05-03 06 50 57" src="https://cloud.githubusercontent.com/assets/624760/14975637/ba64f272-10fb-11e6-846e-777bdef4881d.png">

Hopefully I am not forgetting anyone 😕

**Comment by squeakcode** [comment]
Aww thanks, that's so sweet! :)
Can't decide if I prefer the website or the YT channel to be linked.

**Comment by eddiejaoude** [comment]
Credit where credit is due 😉

No problem, let me know. I haven't put it live yet, I wanted to get the _ok_ from both of you & then style it more. We can always change the link if you change your mind.

**Comment by charlottebrf** [comment]
Happy to be @eddiejaoude @squeakcode - however unsure I've been so helpful!

**Comment by eddiejaoude** [comment]
You both have been extremely helpful 😄

**Comment by eddiejaoude** [comment]
@squeakcode I think website over youtube channel. Will you embed videos from youtube, similar to WRT?
