### ISSUE TITLE
Improve Future Episodes page with photo

### ISSUE THREAD

**Issue by eddiejaoude** [WeRockTech/werocktech.github.io#19]

**Comment by eddiejaoude** [comment]
<img width="1166" alt="screenshot 2016-05-03 06 01 26" src="https://cloud.githubusercontent.com/assets/624760/14974991/8063d112-10f4-11e6-9877-ce573d5105a4.png">

**Comment by charlottebrf** [comment]
This looks awesome

On 3 May 2016 at 06:01, Eddie Jaoude notifications@github.com wrote:

> Closed #19 https://github.com/WeRockTech/werocktech.github.io/issues/19.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/WeRockTech/werocktech.github.io/issues/19#event-648426398

## 

---

_Charlotte Fereday_

Programmes Manager @codefirstgirls

Tweeting & retweeting @charlottebrf

*Mainly: Tech/Education/Hispanic studies *
