### ISSUE TITLE
Intro video to CF:G & OnesToWatch

### ISSUE THREAD

**Issue by eddiejaoude** [WeRockTech/werocktech.github.io#20]
Ideas:
- [ ] Who are CF:G
- [ ] Who are the OnesToWatch
- [ ] How can others join for next year
- [ ] ...

**Comment by charlottebrf** [comment]
Thanks Eddie- looking good!

On 8 June 2016 at 08:15, Eddie Jaoude notifications@github.com wrote:

> Closed #20 https://github.com/WeRockTech/werocktech.github.io/issues/20.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/WeRockTech/werocktech.github.io/issues/20#event-685379810,
> or mute the thread
> https://github.com/notifications/unsubscribe/AQGk-GGJ1BImfRuoX8JiXWkiMliZGBdLks5qJmwdgaJpZM4IW4AA
> .

## 

---

_Charlotte Fereday_

Programmes Manager @codefirstgirls

Tweeting & retweeting @charlottebrf

*Mainly: Tech/Education/Hispanic studies *
